# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Injulkar Nilesh"
description: > # this means to ignore newlines until "email:"
   Code. Read. Trek.

email: injulkarnilesh@gmail.mail
#blog logo
logo: "/assets/images/df_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Nilesh Injulkar'
author: 'Nilesh Injulkar'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://injulkarnilesh.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
disqus: injulkarnilesh-github-io

google_analytics: UA-160621840-2

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/injulkarnilesh/
    desc: Connect with me on Linkedin
    share_url:
    share_title: 
    share_link:

  - icon:	github
    url:	https://github.com/injulkarnilesh
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	book
    url:	https://www.goodreads.com/user/show/18638623-nilesh-injulkar
    desc: Read with me
    share_url:
    share_title:
    share_link:

gems:
  - jekyll-sitemap